---
- name: Add fish to shell
  ansible.builtin.lineinfile:
    group: wheel
    mode: "0644"
    owner: root
    path: /etc/shells
    line: /opt/homebrew/bin/fish
  become: true
  register: setshell
- name: Set fish as the default shell
  ## Modified from
  ## https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
  ansible.builtin.command: chsh -s /opt/homebrew/bin/fish '{{ ansible_user }}'
  become: true
  when: setshell
  changed_when: false
- name: Create fish config directory
  become: false
  ansible.builtin.file:
    group: "{{ ansible_group }}"
    mode: "0755"
    owner: "{{ ansible_user }}"
    path: ~/.config/fish
    state: directory
- name: Copy config.fish
  become: false
  ansible.builtin.template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish
    group: "{{ ansible_group }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
