---
- name: Generate gitconfig
  become: false
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_user_dir }}/.gitconfig"
    group: "{{ ansible_group }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
